inveniosoftware/invenio-files-rest

.travis.yml
invenio_files_rest/config.py
invenio_files_rest/ext.py
invenio_files_rest/permissions.py
invenio_files_rest/views.py
setup.py
tests/conftest.py
tests/test_views.py

* Adds permissions to files REST.

global: adds permissions

---

invenio_files_rest/views.py
setup.py
tests/conftest.py
tests/test_views_records_ui.py

* Adds pluggable file download view for Records-UI.

views: records-ui file download view

---

invenio_files_rest/views.py

* Changes the 'key' argument type in URL pattern to path.

global: URL key as path

---

AUTHORS.rst
invenio_files_rest/errors.py
invenio_files_rest/ext.py
invenio_files_rest/helpers.py
invenio_files_rest/models.py
invenio_files_rest/storage.py
invenio_files_rest/views.py
tests/conftest.py
tests/test_helpers.py
tests/test_storage.py
tests/test_views.py

* NEW Adds bucket quota validation when files are added (closes #25).
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>

global: new bucket quota validation

---

docs/api.rst
invenio_files_rest/config.py
invenio_files_rest/models.py
tests/test_models.py

* Changes the type of file URI and object key to db.Text with validation.

global: object key and file uri db type change

---

AUTHORS.rst
invenio_files_rest/__init__.py
invenio_files_rest/config.py
invenio_files_rest/errors.py
invenio_files_rest/ext.py
invenio_files_rest/helpers.py
invenio_files_rest/limiters.py
invenio_files_rest/models.py
invenio_files_rest/permissions.py
invenio_files_rest/proxies.py
invenio_files_rest/storage.py
invenio_files_rest/views.py
run-tests.sh
tests/conftest.py
tests/test_limiters.py
tests/test_views.py

* Adds a per bucket maximum file size limit.
* File size limits are now checked while writing the object.
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>

models: per bucket file size limits

---

invenio_files_rest/ext.py

* FIX Fixes missing return statement in
`_FilesRESTState.record_file_factory()`.
Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

ext: missing return

---

RELEASE-NOTES.rst
examples/app.py
setup.py
tests/conftest.py

* Changes `invenio-software.org` to `inveniosoftware.org` to use the
same dashless canonical ID everywhere (GitHub, Twitter, Web).
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

global: inveniosoftware.org

---

invenio_files_rest/errors.py

* Sets 403 as code for InvalidOperationError.
(closes inveniosoftware/invenio-deposit#91)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

errors: InvalidOperationError 403 code setting

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_files_rest/version.py
invenio_files_rest/views.py

* On stream uploads, sets the Content-Type header to and
empty string ('') if missing.
Co-authored-by: Krzysztof Nowak <k.nowak@cern.ch>

views: handle missing Content-Type

---

invenio_files_rest/helpers.py
invenio_files_rest/storage/base.py
run-tests.sh
tests/conftest.py
tests/test_views_objectversion.py

* Fixes the incorrect conversion of last modified timestamps
from localtime to UTC.

global: fix the last modified conversion

---

invenio_files_rest/views.py
tests/test_views_location.py

* Fixes issue with GET request to LocationResource replying with 500
error instead of 405.

views: bad response code fix

---

invenio_files_rest/models.py
invenio_files_rest/storage/base.py
invenio_files_rest/tasks.py
tests/test_tasks.py

* Adds an additional `checksum_kwargs` parameter to
`FileInstance.verify_checksum` that is passed as `**kwargs` to
`storage().checksum`.

models: checksum_kwargs addition

---

CHANGES.rst
RELEASE-NOTES.rst
examples/app.py
invenio_files_rest/models.py
invenio_files_rest/version.py

* Avoids updating location timestamps when creating buckets. This update
is problematic when many concurrent tasks are creating buckets since
the same row gets updated and can lead to deadlocks in the database.
Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>

models: no location timestamp update on bucket creation

---

invenio_files_rest/config.py
invenio_files_rest/tasks.py

* Passes `checksum_kwargs` correctly to the `verify_checksum` task.
* Adds a `files_query` argument for allowing different task
configurations.

tasks: checksum schedule task argument fixes

---

invenio_files_rest/models.py
tests/test_models.py

Closes https://github.com/inveniosoftware/invenio-files-rest/issues/171, but I'm not fully convinced that this is the best solution for the problem as all those small classes looks a bit clunky. It's also missing tests as they seem tricky to write, and if this solution is not going in the right direction then it would have been a waste of effort...

models: JSON-friendly errors in ensure_state

---

invenio_files_rest/views.py
setup.py

Changed the default arguments
for args that are both optional
and don't define `missing`
from `None` to `marshmallow.missing`.
I verified that the tests are passing
locally with the following webargs installations:
* latest `dev` branch
* webargs==5.1.0 (latest stable)
* webargs<5.0 (4.4.1 as of this writing)
* webargs==1.1.1 (min version in setup.py)
see #184

views: fix compatibility with webargs 5.x

---

invenio_files_rest/errors.py

* The `StorageError` class is used in the codebase
by passing a string as error. Due to the fact that
inherits from the `RESTException` class, which assumes
that the errors are a list, it was throwing a syntax error
hiding the actual one.
closes inveniosoftware/invenio-rest#99

errors: handle string error messages

---

invenio_files_rest/alembic/a29271fd78f8_create_files_object_partial_unique_index.py
invenio_files_rest/models.py
tests/test_invenio_files_rest.py
tests/test_models.py

Avoid inconsistent state on DB on race conditions.
For postgresql only. Mysql does not  support unique partial constraints.
Changes: 
- Model: add constraint to enforce only one object version is head
- Alembic: add migration

files_object: enforce unique is_head =True on postgresql

---

invenio_files_rest/views.py

This PR removes the RemovedInMarshmallow4Warning warning by updating the code to the new interface of marshmallow.Field.
It was necessary to wrap parameters (load_from, location) into a dictionary to give to the parameter metadata. Further the missing parameter has to be changed to load_default.

Remove deprecation warnings from marshmallow

---

invenio_files_rest/tasks.py
setup.cfg
tests/test_tasks.py

This PR adds a background task that deletes orphaned files from DB and disk (i.e. `FileInstance`s that don't have any `ObjectVersion`s linked with them anymore).
It is a slightly adapted version of our custom CLI command: https://gitlab.tuwien.ac.at/fairdata/invenio-utilities-tuw/-/blob/master/invenio_utilities_tuw/cli/files.py#L240
**Note**: The CLI command has been working well enough to clean up unreferenced files of deleted drafts, but I found that the `force` flag has to be provided because the storage is marked as not `writable`.
I'll still add tests for the new task, and then mark this as ready for review.

Add task for cleaning up orphan files

---

CHANGES.rst
docs/conf.py
invenio_files_rest/__init__.py
setup.cfg
tests/conftest.py

- migrate: flask_babelex replaced by invenio_i18n
- fix: celery.contrib.sphinx make problems
- NOTE flask-security-invenio, invenio-i18n, invenio-admin, invenio-accounts, invenio-theme have to be released first

migrate to flask babel

---

invenio_files_rest/storage/pyfs.py

Opening a file fails if the user does not have write permissions. The  `open` seems to call mkdir, and that fails. 
This patch avoids creating directories if the file is opened only for reading.

files: avoid creating directories while opening files for reading

---

invenio_files_rest/__init__.py
setup.cfg
tests/conftest.py

Fix failing tests
```log
tests/conftest.py:27: in <module>
from invenio_accounts.views import blueprint as accounts_blueprint
E   ImportError: cannot import name 'blueprint' from 'invenio_accounts.views' (/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/invenio_accounts/views/__init__.py)
```
- This commit addresses compatibility issues caused by the recent API changes in the `invenio-accounts` module that is introduced in [this commit](https://github.com/Samk13/invenio-accounts/commit/5e1c58394d464d199d183302f65ab2084e08b621). It removes the usage of `accounts_blueprint` from invenio_files_rest and related tests, as it is no longer required and causes failures in the continuous integration (CI) tests. The change is aligned with …

Fix: Apply `invenio-accounts` API Changes

---

.github/workflows/tests.yml
invenio_files_rest/helpers.py
tests/test_views_multipart.py

one of our invenio-users at TU Graz uploaded a file named *Erläuterungen zum Analysebogen digitaler Schulbücher 1-2 (Design, Technik, Barrierefreiheit)* ([link to record-page](https://repository.tugraz.at/oer/yzhp8-7ay47))
attempting to download this file from Google Chrome fails with `net::ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION`
the same issue occurs for a vanilla invenio-installation:
this download-failure occurs for the following filenames (seemingly independent of file-content):
- has a file-extension for which a *Content-Disposition* header is generated, e.g. `.docx`
- contains a comma (`,`) character
- is NOT `latin-1`-encodable
simplest example I could find is `ä, B.docx` (file-contents are an empty `.docx` file)
note that `ä`'s unicode-codepoints here are …

fix: fix downloading for non-latin-1 filenames containing a comma

---

invenio_files_rest/formparser.py
invenio_files_rest/models.py
invenio_files_rest/tasks.py

* to keep the functionality as it is, a method from werkzeug have been
copy pasted over and changed slightly.

fix: compatibility with werkzeug >= 3.0.0.

---

invenio_files_rest/storage/base.py
setup.cfg

> Please describe briefly your pull request.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …

i18n: Mark Missing Translations

---

CHANGES.rst
invenio_files_rest/__init__.py
invenio_files_rest/storage/base.py
setup.cfg

> Please describe briefly your pull request.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license your contribution under the …

I18n: Mark Missing Translations Backport

---

invenio_files_rest/admin.py
invenio_files_rest/helpers.py
invenio_files_rest/tasks.py
tests/test_tasks.py

`FileInstance` can be marked as non-readable. Currently, even those instances are read during checksum verification, which might raise an exception during file opening/reading. 
This commit fixes that by adding `readable=True` to the default checksum verification filter and changing the way the total size is computed to take this filter into account.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of …

fix: skip non-readable files on checksum verification
