- .editorconfig
- invenio_files_rest/admin.py
- invenio_files_rest/errors.py
- invenio_files_rest/ext.py
- invenio_files_rest/helpers.py
- invenio_files_rest/models.py
- invenio_files_rest/signals.py
- invenio_files_rest/storage.py
- invenio_files_rest/views.py
- run-tests.sh
- setup.py
- tests/conftest.py
- tests/test_models.py
- tests/test_storage.py
- tests/test_views.py
- tests/test_views_object.py
* Refactors models to support sharing the same files between multiple buckets.
> global: refactoring of models

- .gitignore
- .travis.yml
- examples/app.py
- invenio_files_rest/admin.py
- invenio_files_rest/ext.py
- invenio_files_rest/models.py
- setup.py
- tests/conftest.py
- tests/test_models.py
* Adds fixture data for example application.
> examples: fixture data for application

- invenio_files_rest/models.py
* Adds support for chaining methodds.
> models: minor fix

- invenio_files_rest/ext.py
- invenio_files_rest/permissions.py
- invenio_files_rest/proxies.py
- invenio_files_rest/views.py
- setup.py
* Fixes issue with hard dependency with Invenio-Access.
> permissions: isolate invenio-access imports

- .travis.yml
- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_files_rest/version.py
> release: v1.0.0a1

- .travis.yml
- invenio_files_rest/version.py
> version: post-release bump

- invenio_files_rest/views.py
Signed-off-by: Emanuel Dima <emanueldima@gmail.com>
Closes #50
> bug fix: rename filename to key in DELETE and HEAD http calls

- AUTHORS.rst
- invenio_files_rest/models.py
- invenio_files_rest/storage.py
- invenio_files_rest/views.py
> global: MIME type for ObjectVersion

- .editorconfig
- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_files_rest/cli.py
- invenio_files_rest/config.py
- invenio_files_rest/ext.py
- invenio_files_rest/signals.py
- invenio_files_rest/version.py
- invenio_files_rest/views.py
- setup.py
- tests/test_views_records_ui.py
* Adds customizable record file factory responsible extracting files
from records.
* Sends file-downloaded signal.
> global: record file factory

- tests/test_views_records_ui.py
* Updates tests using the RecordsBuckets api.
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>
> tests: amend RecordsBuckets api usage

- docs/conf.py
- invenio_files_rest/config.py
- invenio_files_rest/ext.py
- invenio_files_rest/storage.py
- setup.py
- tests/test_storage.py
- tests/test_tasks.py
* Adds the possiblity to store the files grouped by file name in
different directories. (closes #64)
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>
> storage: addition of hierarchical directory

- docs/conf.py
- invenio_files_rest/models.py
- invenio_files_rest/views.py
- tests/test_models.py
* Adds hybrid property for computing MIME type if no default type is
set.
> models: hybrid object mimetype property

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_files_rest/version.py
> release: v1.0.0a4

- .travis.yml
- examples/app.py
- invenio_files_rest/config.py
- invenio_files_rest/errors.py
- invenio_files_rest/ext.py
- invenio_files_rest/serializer.py
- invenio_files_rest/views.py
- run-tests.sh
- tests/test_views_multipart.py
- tests/test_views_objectversion.py
> views: ng-file-upload support fix

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_files_rest/version.py
> release: v1.0.0a5

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_files_rest/version.py
> release: v1.0.0a7

- examples/app.py
- invenio_files_rest/cli.py
- setup.py
- tests/conftest.py
- tests/test_cli.py
* Removes dependency on Flask-CLI.
> installation: Flask>=0.11

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_files_rest/version.py
> release: v1.0.0a9

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_files_rest/version.py
> release: v1.0.0a10

- docs/api.rst
- docs/conf.py
- invenio_files_rest/app.py
- invenio_files_rest/config.py
- invenio_files_rest/helpers.py
- invenio_files_rest/limiters.py
- invenio_files_rest/models.py
- invenio_files_rest/permissions.py
- invenio_files_rest/proxies.py
- invenio_files_rest/serializer.py
- invenio_files_rest/storage/base.py
- invenio_files_rest/tasks.py
- invenio_files_rest/views.py
* Improves documentation. (addresses #89)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
> docs: addition of param and result sections

- invenio_files_rest/config.py
- tests/test_models_multipart.py
> global: file size comment fix

- examples/app-fixtures.sh
- examples/app-setup.sh
- examples/app-teardown.sh
- examples/app.py
- examples/requirements.txt
- tests/test_examples_app.py
* Adds test_examples_app.py. (closes #113)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
> tests: addition of test_examples_app.py

- invenio_files_rest/ext.py
- invenio_files_rest/utils.py
Closes #101 
Signed-off-by: Alizee Pace <alizee.pace@gmail.com>
> utils: addition of callables in factories

- README.rst
- RELEASE-NOTES.rst
- invenio_files_rest/ext.py
- invenio_files_rest/utils.py
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
> docs: move to readthedocs.io

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_files_rest/version.py
> release: v1.0.0a12

- invenio_files_rest/models.py
Signed-off-by: Sebastian Witowski <witowski.sebastian@gmail.com>
> docs: ObjectVersion.basename docstring fix

- MANIFEST.in
- examples/app-setup.sh
- examples/app-teardown.sh
- examples/app.py
- invenio_files_rest/alembic/2e97565eba72_create_files_rest_tables.py
- invenio_files_rest/alembic/52ce868f33c3_create_files_rest_branch.py
- setup.py
- tests/conftest.py
- tests/test_invenio_files_rest.py
> global: initial alembic recipes

- CHANGES.rst
- MANIFEST.in
- RELEASE-NOTES.rst
- examples/app-setup.sh
- examples/app-teardown.sh
- examples/app.py
- invenio_files_rest/alembic/2e97565eba72_create_files_rest_tables.py
- invenio_files_rest/alembic/52ce868f33c3_create_files_rest_branch.py
- invenio_files_rest/version.py
- setup.py
- tests/conftest.py
- tests/test_invenio_files_rest.py
New release in order to unblock inveniosoftware/invenio-records-files#38 even though #132 and #133 are almost ready.
> release: v1.0.0a14

- .editorconfig
- invenio_files_rest/alembic/2e97565eba72_create_files_rest_tables.py
- invenio_files_rest/models.py
- setup.py
> models: forced name of Boolean column

- setup.py
> installation: sphinx version fix

- invenio_files_rest/storage/base.py
* FIX Ensures the file pointer is correctly closed.  (closes #141)
> storage: fix file pointer context

- examples/app-teardown.sh
- invenio_files_rest/ext.py
- invenio_files_rest/helpers.py
- invenio_files_rest/limiters.py
- invenio_files_rest/models.py
- invenio_files_rest/permissions.py
- invenio_files_rest/serializer.py
- invenio_files_rest/storage/base.py
- invenio_files_rest/storage/pyfs.py
- invenio_files_rest/views.py
- setup.py
- tests/conftest.py
- tests/test_models.py
* Fixes issue about double head when delete an object and create
again. (closes #145)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
> models: fix double heads on delete/create

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_files_rest/version.py
> release: v1.0.0a15

- CHANGES.rst
- invenio_files_rest/version.py
> global: version and license date bump

- invenio_files_rest/helpers.py
- tests/test_storage.py
* Prevents Content-Disposition for being added twice.
* Adds extra tests for XSS prevention.
> storage: content disposition fix

- invenio_files_rest/helpers.py
- tests/test_storage.py
> storage: content-disposition unicode filename fix

- .travis.yml
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>
> test: make travis' mysql devel build mandatory

- invenio_files_rest/helpers.py
- invenio_files_rest/models.py
- invenio_files_rest/storage/base.py
- invenio_files_rest/tasks.py
* Fixes issue with a default chunk size not being set when verifiying
the checksum of a file instance, causing an entire file to be read
into memory. Eventually this could lead to segmantation faults when
trying to read very large files.
* Adds support for specifying override chunk size from API.
> storage: default chunk size for checksum fix

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_files_rest/version.py
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>
> release: v1.0.0a21

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_files_rest/version.py
https://github.com/inveniosoftware/invenio-files-rest/issues/171 is happening on our production system, so a new release will fix the issue on our next deploy.
> release: v1.0.0a22

- invenio_files_rest/models.py
- invenio_files_rest/storage/base.py
- invenio_files_rest/views.py
- setup.py
- tests/conftest.py
- tests/test_storage.py
- tests/test_views_objectversion.py
> rest: support download file

- invenio_files_rest/serializer.py
- tests/test_serializer.py
> serializer: drop usage of request.is_xhr for JSON

- examples/app.py
> example_app: updating docstring instructions

- invenio_files_rest/models.py
- invenio_files_rest/utils.py
- tests/test_models.py
Adds the following mimetypes:
- 'application/gzip'
- 'application/gzip'
- 'application/x-bzip2'
- 'application/x-xz'
> mimetypes: improve detection

- examples/app.py
- invenio_files_rest/permissions.py
- tests/conftest.py
- tests/test_examples_app.py
- tests/test_views_multipart.py
- tests/test_views_objectversion.py
> permissions: change permission class

- invenio_files_rest/__init__.py
> global: fixes sorting according to isort

- invenio_files_rest/views.py
- tests/test_views_objectversion.py
* If head version of object is deleted, sets newest version as head.
Closes #144
> views: sets head object after deletion          

- setup.py
* Closes inveniosoftware/invenio#3940
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>
> global: pytest v3.7.0

- invenio_files_rest/views.py
- tests/test_views_multipart.py
* In the case of having an external library which has already
read the `request.stream` files REST fails with a server error
since it will not be able to read the uploaded file.
This has happened with Sentry's `raven-python` library which
reads the stream when the mimetype is `application/json` causing
JSON files uploads to not work and throwing a misleading error.
More here
https://github.com/getsentry/raven-python/blob/719be9afae528962e683d086f9c2ceeda07f881b/raven/contrib/flask.py#L198
Now a proper error is thrown (closes #197).
> views: detect if input stream was already read

- invenio_files_rest/errors.py
- invenio_files_rest/views.py
* Closes #197 and addresses comment
https://github.com/inveniosoftware/invenio-files-rest/pull/207#discussion_r285901293
> errors: add custom error for exhausted streams

- invenio_files_rest/models.py
- tests/test_models.py
* Adding unicode support for ObjectVersion. Closes #178
> models: adding unicode support

- CHANGES.rst
- invenio_files_rest/version.py
> release: v1.0.0

- CHANGES.rst
- invenio_files_rest/version.py
> release: v1.0.1

- invenio_files_rest/signals.py
- invenio_files_rest/tasks.py
- invenio_files_rest/views.py
- tests/test_signals.py
Simple tests for signals 
- file_uploaded
- file_deleted
> tests: signals

- invenio_files_rest/models.py
> typo: danshes -> dashes

- invenio_files_rest/cli.py
- invenio_files_rest/version.py
- setup.py
- tests/test_cli.py
Fix backwards compatibility of `invenio files location` (make that still possible and default to `create` command which was the functionality before).
> Release v1.1.1

- CHANGES.rst
- invenio_files_rest/helpers.py
- invenio_files_rest/version.py
closes https://github.com/inveniosoftware/invenio-files-rest/issues/248
> release: v1.2.0

- .github/workflows/i18n-pull.yml
- .github/workflows/i18n-push.yml
- .github/workflows/tests.yml
- babel.ini
- invenio_files_rest/alembic/2e97565eba72_create_files_rest_tables.py
- run-i18n-tests.sh
- run-tests.sh
- tests/test_storage.py
test: adds extract_messages dry command
> ci: adds i18n workflow

- CHANGES.rst
- invenio_files_rest/__init__.py
- invenio_files_rest/models.py
- run-tests.sh
- setup.cfg
- tests/conftest.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2259
> models: change object_version.sync method to return changes

- .github/workflows/tests.yml
- invenio_files_rest/models.py
- invenio_files_rest/storage/pyfs.py
- setup.cfg
* closes https://github.com/zenodo/rdm-project/issues/253
* closes https://github.com/inveniosoftware/invenio-records-resources/issues/319
this and dependent PRs need to be reviewed and tested **very** thoroughly
> File upload interruption

- CHANGES.rst
- invenio_files_rest/__init__.py
Please describe briefly your pull request.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
> release: v2.0.1

- invenio_files_rest/models.py
- tests/test_models.py
* Closes https://github.com/zenodo/rdm-project/issues/413
> models: add remove-many

- CHANGES.rst
- invenio_files_rest/__init__.py
Please describe briefly your pull request.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
> release: v2.0.3

- invenio_files_rest/models.py
- tests/test_models.py
* closes https://github.com/zenodo/rdm-project/issues/508
> Add autoflush to get file

- invenio_files_rest/serializer.py
- setup.cfg
Fix tests by updating pytest-black-ng dep
> CI: Resolve Failing Test

- .github/workflows/pypi-publish.yml
- CHANGES.rst
- invenio_files_rest/__init__.py
- setup.cfg
- setup: pin dependencies
- release: v2.2.3
> pin dependencies

- .github/workflows/pypi-publish.yml
- CHANGES.rst
- invenio_files_rest/__init__.py
- workflows: add translation flag for publishing
- release: v2.2.4
> fix translations 2

- CHANGES.rst
- docs/conf.py
- invenio_files_rest/__init__.py
- invenio_files_rest/alembic/8ae99b034410_create_files_objecttags_table.py
- invenio_files_rest/helpers.py
- setup.cfg
- tests/conftest.py
- tests/test_request.py
- tests/test_views_multipart.py
- tests/test_views_objectversion.py
- tests/testutils.py
- setup: bump invenio dependencies
- release: v3.0.0
> bump major
